-- CreateTable
CREATE TABLE "User" (
    "id" SERIAL NOT NULL,
    "usuario" TEXT NOT NULL,
    "correo" TEXT NOT NULL,
    "genero" TEXT NOT NULL,
    "contrasena" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "User_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "MedicalRecord" (
    "id" TEXT NOT NULL,
    "numero_historia_clinica" TEXT NOT NULL,
    "nombre_paciente" TEXT NOT NULL,
    "tipo_identificacion" TEXT NOT NULL,
    "edad" TEXT NOT NULL,
    "fecha_nacimiento" TEXT NOT NULL,
    "escolaridad" TEXT,
    "ocupacion" TEXT,
    "lugar_nacimiento" TEXT,
    "nacionalidad" TEXT,
    "religion" TEXT,
    "direccion_residencia" TEXT,
    "barrio" TEXT,
    "ciudad" TEXT,
    "departamento" TEXT,
    "fecha_ingreso" TEXT NOT NULL,
    "celular" TEXT,
    "telefono" TEXT,
    "e_mail" TEXT,
    "eps" TEXT,
    "cotizante" TEXT,
    "beneficiario" TEXT,
    "remitido_por" TEXT,
    "responsable1_nombre" TEXT,
    "responsable1_parentesco" TEXT,
    "responsable1_celular" TEXT,
    "responsable1_ocupacion" TEXT,
    "responsable2_nombre" TEXT,
    "responsable2_parentesco" TEXT,
    "responsable2_celular" TEXT,
    "responsable2_ocupacion" TEXT,
    "atendido_por" TEXT,
    "antecedentes_personales" TEXT,
    "antecedentes_patologicos" TEXT,
    "antecedentes_quirurgicos" TEXT,
    "antecedentes_psicopatologicos" TEXT,
    "historia_de_trauma_o_abuso" TEXT,
    "estado_del_sueno" TEXT,
    "consumo_sustancias" TEXT,
    "antecedentes_familiares_patologicos" TEXT,
    "antecedentes_familiares_traumaticos" TEXT,
    "antecedentes_familiares_consumo" TEXT,
    "embarazo" TEXT,
    "parto" TEXT,
    "desarrollo_psicomotor" TEXT,
    "dinamica_familiar" TEXT,
    "motivo_consulta" TEXT,
    "historia_del_problema" TEXT,
    "expectativa_terapia" TEXT,
    "examen_mental" TEXT,
    "evaluacion_psicologica" TEXT,
    "idx_o_dx" TEXT,
    "objetivos_terapeuticos" TEXT,
    "plan_terapeutico" TEXT,
    "derivacion_o_remision" TEXT,
    "recomendaciones" TEXT,
    "evolucion_nombre" TEXT,
    "evolucion_historia_no" TEXT,
    "evolucion" TEXT,
    "digitado_por" TEXT,
    "createdAt" TEXT NOT NULL DEFAULT 'now',
    "updatedAt" TEXT NOT NULL DEFAULT 'now',

    CONSTRAINT "MedicalRecord_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "User_correo_key" ON "User"("correo");
